---
title: Women in Power
author: Robert Myles McDonnell
date: '2017-09-19'
slug: women-in-power
categories: [ggplot2, R, visualization]
tags: []
draft: true
---

```{r, message=FALSE}
library(dplyr); library(readxl)
columns <- c("Country", "Overall Index", "Overall Rank",
             "Economic Participation & Opportunity", "Eco Rank",
             "Educational Attainment", "Edu Rank",
             "Health and Survival", "Health Rank",
             "Political Empowerment", "Poli Rank")
df <- read_excel("/Users/robert/Downloads/WEF_GGGR_Dataset_2016.xlsx", sheet = 2,
                 skip = 3, col_names = columns)

```

```{r}
library(ggplot2); library(tidyr); library(extrafont)
#font_import()
#loadfonts()

df %>% 
   ggplot(aes(x = `Health and Survival`)) + 
   geom_density()

df %>%
  gather(key = "Index Type", value = "Value", `Economic Participation and Opportunity`,
         `Educational Attainment`, `Health and Survival`,
         `Political Empowerment`) %>% {
           ggplot(., aes(x = Value, colour = `Index Type`)) +
             geom_density() +
             #geom_density(data = filter(., `Index Type` == "Economic Participation and Opportunity")) +
             #geom_density(data = filter(., `Index Type` == "Educational Attainment")) +
             #geom_density(data = filter(., `Index Type` == "Health and Survival")) +
             #geom_density(data = filter(., `Index Type` == "Political Empowerment")) +
             facet_wrap(~ `Index Type`, scales = "fixed")
         }
df %>% 
  gather(key = "Index Type", value = "Value", `Economic Participation and Opportunity`,
         `Educational Attainment`, `Health and Survival`,
         `Political Empowerment`) %>%
  group_by(`Index Type`) %>% 
  summarise(mean = mean(Value)) %>% 
  ggplot(aes(x = reorder(as.factor(`Index Type`), mean), y = mean, fill = mean)) + 
  geom_col(colour = "#243B4A") + 
  coord_flip() + theme_minimal() + 
  scale_fill_continuous(high = "#D3D0CB", low = "#2D4654") +
  theme(text = element_text(family = "Slabo 27px", size = 14),
        legend.position = "none") + labs(x = NULL, y = NULL)
```



d3 click on category, shows countries. Or click on map, shows country details. 


